<?php

namespace App\Traits;

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

trait SharedMethod
{

    // ========================================================================
    // ===================== Get Auth User Type Function ======================
    // ==================== Created By : Layth Al-Dwairi ======================
    // ========================================================================
    public function authUserType()
    {
        if (Auth::guard('super_admin')->check()) {
            return 'Super Admin';
        } elseif (Auth::guard('customer')->check()) {
            return 'Customer';
        } else {
            return 'undefined';
        }
    }

    // ========================================================================
    // ======================== Set Job Read Function =========================
    // ==================== Created By : Layth Al-Dwairi ======================
    // ========================================================================
    protected function closeDatabase()
    {
        // parent::closeDatabase(); // Change the autogenerated stub
        $uses = array_flip(class_uses_recursive(static::class));
        if (isset($uses[DatabaseMigrations::class])) {
            $this->beforeApplicationDestroyed(function () {
                $this->app->make('db')->connection('jmegoods_v1')->disconnect();
            });
            DB::disconnect('jmegoods_v1');
        }
    }

}
